### PR TITLE
Submission Sprint 1

### PR DESCRIPTION
**Pull request by adi64**
Contributors:
@adi64
@ldurdel
@atix

### CODE REVIEW

**Comment by Bensk1** [comment]
Hallo ich bin der erste Kommentar

File: src/lib/storage/table.cpp [hunk 1]
```diff
@@ -17,61 +17,111 @@
...
+void Table::_create_missing_columns() {
+  DebugAssert(_column_names.size() == _column_types.size(), "Every column needs a name and type");
+
+  Chunk& lastChunk = _chunks.back();
+
+  // Assuming that columns may only be created, we can assume that already existing columns match
+  // our stored definition
+  auto firstMissingColumnIndex = lastChunk.col_count();
+
+  for (auto index = firstMissingColumnIndex; index < _column_types.size(); ++index) {
```
Comment (ldurdel) [inline src/lib/storage/table.cpp]: Replace with range based for.

File: src/lib/storage/chunk.cpp [hunk 2]
```diff
@@ -14,27 +14,29 @@
...
+  for (size_t i_column = 0; i_column < _columns.size(); ++i_column) {
+    _columns[i_column]->append(values[i_column]);
+  }
 }
 
 std::shared_ptr<BaseColumn> Chunk::get_column(ColumnID column_id) const {
-  // Implementation goes here
-  return nullptr;
+  Assert(column_id < _columns.size(), "Column index out of bounds");
+  return _columns[column_id];
```
Comment (ldurdel) [inline src/lib/storage/chunk.cpp]: Consider using `at()`.

File: src/lib/storage/table.cpp [hunk 3]
```diff
@@ -17,61 +17,111 @@
...
-  // Implementation goes here
-  return 0;
+  DebugAssert(_column_names.size() == _column_types.size(), "Every column needs a name and type");
+  return _column_names.size();
 }
 
 uint64_t Table::row_count() const {
-  // Implementation goes here
-  return 0;
+  return std::accumulate(_chunks.cbegin(), _chunks.cend(), 0,
```
Comment (ldurdel) [inline src/lib/storage/table.cpp]: In case `_maximum_column_size > 0` this solution is unnecessarily slow. Provide faster implementation in this case.

File: src/lib/storage/storage_manager.cpp [hunk 4]
```diff
@@ -9,38 +10,39 @@
...
+    const std::string& name = key_value.first;
+    const Table& table = *(key_value.second);
+    out << name << "\t" << table.col_count() << "\t" << table.row_count() << "\t" << table.chunk_count() << "\n";
+  }
 }
 
-void StorageManager::reset() {
-  // Implementation goes here;
-}
+void StorageManager::reset() { _instance = StorageManager{}; }
```
Comment (tim-friedrich) [inline src/lib/storage/storage_manager.cpp]: Do you have any reason for using curly brackets here?

File: src/lib/storage/table.cpp [hunk 5]
```diff
@@ -17,61 +17,111 @@
...
+
 void Table::add_column_definition(const std::string& name, const std::string& type) {
-  // Implementation goes here
+  auto nonEmptyErrorMessage = "Column definition modification may only take place on an empty table";
+  Assert(_chunks.size() == 1, nonEmptyErrorMessage);
+  Assert(_chunks.front().size() == 0, nonEmptyErrorMessage);
+  DebugAssert(_column_names.size() == _column_types.size(), "Every column needs a name and type");
+
+  // This does not work because numeric_limits does not work on STRONG_TYPEDEFs
+  // Assert(_column_names.size() < static_cast<size_t>(std::numeric_limits<ChunkID>::max()), "Too many columns");
```
Comment (tim-friedrich) [inline src/lib/storage/table.cpp]: if it doesnt work fix or remove it.
We would vote for removing the check

File: src/lib/storage/table.cpp [hunk 6]
```diff
@@ -17,61 +17,111 @@
...
+
+  _column_names.emplace_back(name);
+  _column_types.emplace_back(type);
+  _chunk_matches_definitions = false;
```
Comment (tim-friedrich) [inline src/lib/storage/table.cpp]: why maintain extra state while there is already enough information to find out if there are any missing columns in the chunk?

File: src/lib/storage/table.cpp [hunk 7]
```diff
@@ -17,61 +17,111 @@
...
+  }
+  if (_chunk_size != 0 && _chunks.back().size() >= _chunk_size) {
+    create_new_chunk();
+  }
+  _chunks.back().append(values);
 }
 
 void Table::create_new_chunk() {
-  // Implementation goes here
+  Assert(_chunks.size() == 0 || _chunks.back().size() > 0, "Cannot create chunk on top of empty chunk");
```
Comment (tim-friedrich) [inline src/lib/storage/table.cpp]: Please remove that check or make it DebugAssert. This should not happen in a deployed version of the database.

File: src/lib/storage/table.cpp [hunk 8]
```diff
@@ -17,61 +17,111 @@
...
-  return 0;
+  return std::accumulate(_chunks.cbegin(), _chunks.cend(), 0,
+                         [](auto acc, const Chunk& chunk) { return acc + chunk.size(); });
 }
 
-ChunkID Table::chunk_count() const {
-  // Implementation goes here
-  return ChunkID{0};
-}
+ChunkID Table::chunk_count() const { return static_cast<ChunkID>(_chunks.size()); }
```
Comment (tim-friedrich) [inline src/lib/storage/table.cpp]: you can initialize the ChunkID without the cast
ChunkID(this->_chunks.size())

File: src/lib/storage/table.cpp [hunk 9]
```diff
@@ -17,61 +17,111 @@
...
 
 ColumnID Table::column_id_by_name(const std::string& column_name) const {
-  // Implementation goes here
-  return ColumnID{0};
+  DebugAssert(_column_names.size() == _column_types.size(), "Every column needs a name and type");
+  for (auto column_index = 0u; column_index < _column_names.size(); ++column_index) {
```
Comment (tim-friedrich) [inline src/lib/storage/table.cpp]: consider using type definition instead of auto for column_index. 0u is ugly.

File: src/lib/storage/table.cpp [hunk 10]
```diff
@@ -17,61 +17,111 @@
...
+    if (_column_names[column_index] == column_name) {
+      return static_cast<ColumnID>(column_index);
```
Comment (tim-friedrich) [inline src/lib/storage/table.cpp]: see above.

File: src/lib/storage/table.cpp [hunk 11]
```diff
@@ -17,61 +17,111 @@
...
 
-const std::vector<std::string>& Table::column_names() const {
-  throw std::runtime_error("Implement Table::column_names()");
-}
+const std::vector<std::string>& Table::column_names() const { return _column_names; }
 
 const std::string& Table::column_name(ColumnID column_id) const {
-  throw std::runtime_error("Implement Table::column_name");
+  Assert(column_id < _column_names.size(), "column id out of range");
+  return _column_names[column_id];
```
Comment (tim-friedrich) [inline src/lib/storage/table.cpp]: consider using at() (see above)

File: src/lib/storage/table.cpp [hunk 12]
```diff
@@ -17,61 +17,111 @@
...
 }
 
 const std::string& Table::column_type(ColumnID column_id) const {
-  throw std::runtime_error("Implement Table::column_type");
+  Assert(column_id < _column_types.size(), "column id out of range");
+  return _column_types[column_id];
```
Comment (tim-friedrich) [inline src/lib/storage/table.cpp]: see above

File: src/lib/storage/table.cpp [hunk 13]
```diff
@@ -17,61 +17,111 @@
...
 }
 
-Chunk& Table::get_chunk(ChunkID chunk_id) { throw std::runtime_error("Implement Table::get_chunk"); }
+Chunk& Table::get_chunk(ChunkID chunk_id) {
+  Assert(chunk_id < _chunks.size(), "chunk id out of range");
+  return _chunks[chunk_id];
```
Comment (tim-friedrich) [inline src/lib/storage/table.cpp]: see above

File: src/lib/storage/table.cpp [hunk 14]
```diff
@@ -17,61 +17,111 @@
...
+}
 
-const Chunk& Table::get_chunk(ChunkID chunk_id) const { throw std::runtime_error("Implement Table::get_chunk"); }
+const Chunk& Table::get_chunk(ChunkID chunk_id) const {
+  Assert(chunk_id < _chunks.size(), "chunk id out of range");
+  return _chunks[chunk_id];
```
Comment (tim-friedrich) [inline src/lib/storage/table.cpp]: see above

File: src/lib/storage/value_column.cpp [hunk 15]
```diff
@@ -16,19 +16,18 @@ namespace opossum {
 template <typename T>
 const AllTypeVariant ValueColumn<T>::operator[](const size_t i) const {
   PerformanceWarning("operator[] used");
-
-  throw std::runtime_error("Implement ValueColumn::operator[]");
+  Assert(i < _values.size(), "Index is out of bounds");
+  return AllTypeVariant{_values[i]};
```
Comment (tim-friedrich) [inline src/lib/storage/value_column.cpp]: why do you initializing a new AllTypeVariant?
you can use
return _values.at(i);
directly

File: src/lib/storage/chunk.cpp [hunk 16]
```diff
@@ -14,27 +14,29 @@
...
+uint16_t Chunk::col_count() const { return _columns.size(); }
 
 uint32_t Chunk::size() const {
-  // Implementation goes here
-  return 0;
+  if (_columns.size() == 0) {
+    return 0;
+  }
+
+  DebugAssert(_columns.front(), "There should be a column, but it is null");
```
[the remark this answers is not in the document]
Comment (adi64) [reply src/lib/storage/chunk.cpp]: `_columns` is a `vector<shared_ptr<BaseColumn>>` so it could possibly happen that it contains one element that holds a `nullptr`. In this case, calling `_columns.front()->size()` will probably segfault.

File: src/lib/storage/table.cpp (hunk 7 above)
Comment (adi64) [reply src/lib/storage/table.cpp]: Why not? `create_new_chunk()` is a public method that can be called from outside.

File: src/lib/storage/table.cpp (hunk 8 above)
Comment (adi64) [reply src/lib/storage/table.cpp]: Unfortunately this doesn't work with gcc 7.2: 
```
[...]/table.cpp:90: error: narrowing conversion of ‘((const opossum::Table*)this)->opossum::Table::_chunks.std::vector<opossum::Chunk>::size()’ from ‘std::vector<opossum::Chunk>::size_type {aka long unsigned int}’ to ‘uint32_t {aka unsigned int}’ inside { } [-Werror=narrowing]
 ChunkID Table::chunk_count() const { return ChunkID{_chunks.size()}; }
                                                     ~~~~~~~~~~~~^~
```

File: src/lib/storage/table.cpp (hunk 3 above)
Comment (AtiX) [reply src/lib/storage/table.cpp]: Note: As discussed in the seminar meeting, chunks may have different row counts even though table has a non-zero max column size. So iteration over every chunk is necessary nevertheless.
